In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import blimpy as bl
from blimpy import Waterfall
from pathlib import Path
import os

/home/wlll2x/.conda/envs/willvenv/lib/python3.10/site-packages/blimpy/__init__.py:21: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound

# Mars Inventory Csv:

In [2]:
midres_dir = Path("/datag/blpd18/datax/gb_mars/splices")

rows = []

for f in sorted(midres_dir.glob("*.0002.fil")):
    wf = Waterfall(str(f), load_data=False)
    h = wf.header
    
    rows.append({
        "file": f.name,
        "source": h.get("source_name"),
        "nchans": h["nchans"],
        "foff_Hz": h["foff"] * 1e6,  # MHz -> Hz
        "tsamp_s": h["tsamp"],
        "fch1_MHz": h["fch1"],
        "bandwidth_MHz": abs(h["foff"]) * h["nchans"]
    })

df = pd.DataFrame(rows)

df

,file,source,nchans,foff_Hz,tsamp_s,fch1_MHz,bandwidth_MHz
0,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1310720,-2861.022949,1.073742,11251.464844,3750.0
1,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1310720,-2861.022949,1.073742,11251.464844,3750.0
2,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1310720,-2861.022949,1.073742,11251.464844,3750.0
3,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1310720,-2861.022949,1.073742,11251.464844,3750.0
4,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1310720,-2861.022949,1.073742,11251.464844,3750.0
5,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1310720,-2861.022949,1.073742,11251.464844,3750.0

In [3]:
narrow_dir = Path("/datag/blpd18/datax/gb_mars/single_coarse_channel")

rows = []

for f in sorted(narrow_dir.glob("*.h5")):
    wf = Waterfall(str(f), load_data=False)
    h = wf.header
    
    rows.append({
        "file": f.name,
        "source": h.get("source_name"),
        "nchans": h["nchans"],
        "foff_Hz": h["foff"] * 1e6,
        "tsamp_s": h["tsamp"],
        "fch1_MHz": h["fch1"],
        "bandwidth_MHz": abs(h["foff"]) * h["nchans"]
    })

narrow_df = pd.DataFrame(rows)

narrow_df

,file,source,nchans,foff_Hz,tsamp_s,fch1_MHz,bandwidth_MHz
0,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1048576,-2.793968,18.253611,8415.527344,2.929688
1,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1048576,-2.793968,18.253611,8415.527344,2.929688
2,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1048576,-2.793968,18.253611,8415.527344,2.929688
3,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1048576,-2.793968,18.253611,8415.527344,2.929688
4,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1048576,-2.793968,18.253611,8415.527344,2.929688
5,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1048576,-2.793968,18.253611,8415.527344,2.929688

In [4]:

for f in sorted(Path("/datag/blpd18/datax/gb_mars/splices").glob("*.0002.fil")):
    wf = Waterfall(str(f), load_data=False)
    h = wf.header

    print(f.name)
    print("  source :", h.get("source_name"))
    print("  nchans :", h["nchans"])
    print("  foff   :", h["foff"])
    print("  tsamp  :", h["tsamp"])
    print("  fch1   :", h["fch1"])
    print()

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66265_DIAG_Mars2020_0011.rawspec.0002.fil
  source : DIAG_Mars2020
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66578_DIAG_Mars_0012.rawspec.0002.fil
  source : DIAG_Mars
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66892_DIAG_Mars2020_0013.rawspec.0002.fil
  source : DIAG_Mars2020
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67205_DIAG_Mars_0014.rawspec.0002.fil
  source : DIAG_Mars
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67519_DIAG_Mars2020_0015.rawspec.0002.fil
  source : DIAG_Mars2020
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67832_DIAG_Mars_0016.rawspec.0002.fil
  source : DIAG_Mars
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

# Quick Look Plots:

In [5]:
mid_file = "/datag/blpd18/datax/gb_mars/splices/spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66265_DIAG_Mars2020_0011.rawspec.0002.fil"

narrow_file = "/datag/blpd18/datax/gb_mars/single_coarse_channel/spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66265_DIAG_Mars2020_0011.rawspec.0000_diced.h5"

In [6]:
mid = Waterfall(mid_file, load_data=False)
nar = Waterfall(narrow_file, load_data=False)

print(mid.header)
print(nar.header)

{'machine_id': 20, 'telescope_id': 6, 'data_type': 1, 'fch1': 11251.46484375, 'foff': -0.00286102294921875, 'nchans': 1310720, 'source_name': 'DIAG_Mars2020', 'src_raj': <Angle 0. hourangle>, 'src_dej': <Angle 0. deg>, 'az_start': 0.0, 'za_start': 0.0, 'nbits': 32, 'tstart': 59256.76695601852, 'tsamp': 1.073741823999999, 'nifs': 1}
{'DIMENSION_LABELS': array(['time', 'feed_id', 'frequency'], dtype=object), 'az_start': np.float64(0.0), 'data_type': np.int64(1), 'fch1': np.float64(8415.52734375), 'foff': np.float64(-2.7939677238464355e-06), 'machine_id': np.int64(20), 'nbits': np.int64(32), 'nchans': np.int64(1048576), 'nifs': np.int64(1), 'source_name': 'DIAG_Mars2020', 'src_dej': <Angle 0. deg>, 'src_raj': <Angle 0. hourangle>, 'telescope_id': np.int64(6), 'tsamp': np.float64(18.253611007999982), 'tstart': np.float64(59256.76695601852), 'za_start': np.float64(0.0)}

In [7]:
mid_data = Waterfall(mid_file).data
nar_data = Waterfall(narrow_file).data

print(mid_data.shape)
print(nar_data.shape)

(279, 1, 1310720)
(16, 1, 1048576)

In [8]:
mid_freq = (
    mid.header["fch1"]
    + np.arange(mid.header["nchans"]) * mid.header["foff"]
)

nar_freq = (
    nar.header["fch1"]
    + np.arange(nar.header["nchans"]) * nar.header["foff"]
)

print(mid_freq[0], mid_freq[-1])
print(nar_freq[0], nar_freq[-1])

11251.46484375 7501.467704772949
8415.52734375 8412.597659043968

In [10]:
from turbo_seti.find_event.find_event_pipeline import find_event_pipeline

events = find_event_pipeline(
    "mars_single_coarse.lst",
    filter_threshold=3,
    check_zero_drift=False,
    SNR_cut=10,
    on_off_first="ON",
    number_in_cadence=6,
    saving=True
)

print(events)

===========   BEGINNING FIND_EVENT PIPELINE   ===========

Assuming the first observation is an ON

FileNotFoundError: [Errno 2] No such file or directory: 'mars_single_coarse.lst'

In [12]:
#!/usr/bin/env python3

import pandas as pd
import os

# ---------------------------------------------------------
# Path to BLISS output CSV
# ---------------------------------------------------------

csv_path = (
    "/home/wlll2x/midres_narrow/mars_single_coarse_bliss/results_mars_single_coarse/"
    "DIAG_Mars2020_f1_snr3_zero.csv"
)

if not os.path.exists(csv_path):
    raise FileNotFoundError(
        f"Could not find {csv_path}\n"
        "Run: find ~/midres_narrow -name 'DIAG_Mars2020_f1_snr3_zero.csv'"
    )


# ---------------------------------------------------------
# Load BLISS hits
# ---------------------------------------------------------

df = pd.read_csv(csv_path)

print("\nLoaded BLISS hits:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())


# ---------------------------------------------------------
# Known Mars signal recovery test
#
# This is NOT a blind search.
# It checks whether BLISS recovered the
# known turboSETI candidate.
# ---------------------------------------------------------

mars_candidate = df[
    (df["Freq"] > 8414.40) &
    (df["Freq"] < 8414.55) &
    (df["DriftRate"] > -1.0) &
    (df["DriftRate"] < 1.0)
]


print("\n====================================")
print("Known Mars frequency region")
print("====================================")

if len(mars_candidate) == 0:
    print("No hits found near known Mars candidate.")
else:
    print(
        mars_candidate[
            [
                "DriftRate",
                "SNR",
                "Freq",
                "FileID",
                "status"
            ]
        ]
        .sort_values(
            "SNR",
            ascending=False
        )
        .head(30)
        .to_string(index=False)
    )


# ---------------------------------------------------------
# Compare ON/OFF behavior
# ---------------------------------------------------------

print("\n====================================")
print("File distribution")
print("====================================")

if len(mars_candidate) > 0:
    print(
        mars_candidate.groupby("FileID").size()
    )


# ---------------------------------------------------------
# Highest SNR hits overall
# ---------------------------------------------------------

print("\n====================================")
print("Highest SNR BLISS hits")
print("====================================")

print(
    df[
        [
            "DriftRate",
            "SNR",
            "Freq",
            "FileID"
        ]
    ]
    .sort_values(
        "SNR",
        ascending=False
    )
    .head(20)
    .to_string(index=False)
)


print("\nDone.")

Loaded BLISS hits:
(58938, 24)

Columns:
['Unnamed: 0', 'TopHitNum', 'DriftRate', 'SNR', 'Freq', 'ChanIndx', 'FreqStart', 'FreqEnd', 'CoarseChanNum', 'FullNumHitsInRange', 'FileID', 'Source', 'MJD', 'RA', 'DEC', 'DELTAT', 'DELTAF', 'max_drift_rate', 'obs_length', 'Hit_ID', 'status', 'in_n_ons', 'RFI_in_range', 'delta_t']

====================================
Known Mars frequency region
====================================
 DriftRate          SNR        Freq  FileID     status
 -0.316332 21376.123047 8414.468571     NaN on_table_3
 -0.306128 20413.833984 8414.468802     NaN on_table_2
 -0.285719 13711.767578 8414.468933     NaN on_table_1
 -0.275515    25.822626 8414.453450     NaN on_table_1
 -0.285719    22.891119 8414.485051     NaN on_table_1
 -0.336740     6.335413 8414.518572     NaN on_table_3
 -0.122451     5.344178 8414.419967     NaN on_table_3
  0.755115     5.323387 8414.423630     NaN on_table_1
  0.448987     5.253523 8414.406782     NaN on_table_1
 -0.653072     5.082314 8414.511954     NaN on_table_3
 -0.224494     5.033320 8414.519762     NaN on_table_3
  0.846953     5.001891 8414.475016     NaN on_table_1
 -0.071430     4.999459 8414.473999     NaN on_table_1
  0.102043     4.985911 8414.419022     NaN on_table_3
 -0.775523     4.931948 8414.481658     NaN on_table_2
  0.765319     4.926126 8414.402487     NaN on_table_3
  0.479600     4.887742 8414.431863     NaN on_table_3
 -0.846953     4.852427 8414.400762     NaN on_table_3
  0.132655     4.834644 8414.521132     NaN on_table_1
  0.173472     4.797758 8414.513044     NaN on_table_1
  0.316332     4.784653 8414.416209     NaN on_table_2
  0.632664     4.777877 8414.467796     NaN on_table_2
 -0.765319     4.771963 8414.511446     NaN on_table_3
  0.846953     4.768715 8414.410386     NaN on_table_3
  0.387762     4.754746 8414.462625     NaN on_table_1
 -0.469396     4.746666 8414.515722     NaN on_table_3
  0.969404     4.741339 8414.474375     NaN on_table_1
 -0.316332     4.740225 8414.416514     NaN on_table_3
  0.622460     4.717647 8414.402078     NaN on_table_2
  0.816340     4.717611 8414.409518     NaN on_table_2

====================================
File distribution
====================================
Series([], dtype: int64)

====================================
Highest SNR BLISS hits
====================================
 DriftRate          SNR        Freq  FileID
  0.000000 30052.529297 8414.062500     NaN
  0.000000 28151.707031 8414.062500     NaN
 -0.316332 21376.123047 8414.468571     NaN
 -0.306128 20413.833984 8414.468802     NaN
  0.000000 19314.091797 8414.062500     NaN
 -0.285719 13711.767578 8414.468933     NaN
 -4.826613   362.779938 8414.443893     NaN
  4.867430   356.480072 8414.493725     NaN
 -4.836817   324.213623 8414.444961     NaN
  4.898043   197.737396 8414.446439     NaN
 -4.877634    66.907219 8414.393502     NaN
 -4.826613    65.302460 8414.543713     NaN
 -4.857226    62.593864 8414.393767     NaN
  4.877634    60.307644 8414.544021     NaN
  4.918451    43.174603 8414.488818     NaN
 -4.826613    41.135925 8414.393825     NaN
  4.887838    39.942375 8414.543732     NaN
 -4.898043    30.874451 8414.392459     NaN
 -4.836817    26.650461 8414.502212     NaN
 -0.275515    25.822626 8414.453450     NaN

Done.

In [13]:
import pandas as pd
import matplotlib.pyplot as plt


csv_path = (
    "/home/wlll2x/midres_narrow/mars_single_coarse_bliss/results_mars_single_coarse/"
    "DIAG_Mars2020_f1_snr3_zero.csv"
)

df = pd.read_csv(csv_path)


# Select recovered Mars candidate
mars = df[
    (df["Freq"] > 8414.46) &
    (df["Freq"] < 8414.48) &
    (df["DriftRate"] > -0.4) &
    (df["DriftRate"] < -0.2)
]


print(mars[
    [
        "Freq",
        "DriftRate",
        "SNR",
        "status"
    ]
])


plt.figure(figsize=(8,5))


for label, group in mars.groupby("status"):
    plt.scatter(
        group["Freq"],
        group["DriftRate"],
        s=80,
        label=label
    )


plt.axhline(
    -0.309,
    linestyle="--",
    label="TurboSETI drift"
)


plt.xlabel("Frequency (MHz)")
plt.ylabel("Drift Rate (Hz/s)")
plt.title("BLISS Recovery of Mars 2020 Signal")

plt.legend()
plt.grid()

plt.savefig(
    "BLISS_Mars_drift_recovery.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

              Freq  DriftRate           SNR      status
7080   8414.474289  -0.326536      4.525419  on_table_1
7143   8414.474986  -0.316332      3.940798  on_table_1
7163   8414.467851  -0.326536      3.333597  on_table_1
7209   8414.466207  -0.224494      3.119859  on_table_1
7212   8414.470472  -0.326536      3.494201  on_table_1
7223   8414.466087  -0.204085      3.041044  on_table_1
7225   8414.476172  -0.306128      3.715916  on_table_1
7252   8414.469418  -0.255106      3.867196  on_table_1
7282   8414.473118  -0.346945      3.056785  on_table_1
7362   8414.462517  -0.255106      4.661358  on_table_1
7374   8414.467107  -0.204085      3.020195  on_table_1
7390   8414.469711  -0.255106      3.162093  on_table_1
7396   8414.467026  -0.255106      3.241798  on_table_1
7409   8414.469667  -0.234698      3.433796  on_table_1
7434   8414.473073  -0.255106      3.026701  on_table_1
7435   8414.475334  -0.346945      3.610956  on_table_1
7474   8414.468330  -0.357149      3.063644  on_table_1
7479   8414.463614  -0.336740      3.584651  on_table_1
7496   8414.471744  -0.306128      3.083279  on_table_1
7513   8414.476481  -0.234698      3.460526  on_table_1
7536   8414.462707  -0.214289      3.357026  on_table_1
7572   8414.475525  -0.377557      3.559589  on_table_1
7615   8414.468369  -0.265311      3.624114  on_table_1
7618   8414.470425  -0.265311      3.404801  on_table_1
7619   8414.470372  -0.265311      3.271367  on_table_1
7643   8414.470812  -0.295923      3.727762  on_table_1
7686   8414.461936  -0.255106      3.172998  on_table_1
7697   8414.467683  -0.214289      3.367433  on_table_1
7710   8414.475604  -0.234698      3.577583  on_table_1
7742   8414.463484  -0.387762      3.676790  on_table_1
7785   8414.463838  -0.336740      3.078750  on_table_1
7795   8414.469602  -0.316332      3.108258  on_table_1
7797   8414.468933  -0.285719  13711.767578  on_table_1
7849   8414.473904  -0.224494      3.231920  on_table_1
7890   8414.466696  -0.204085      3.552514  on_table_1
7910   8414.476253  -0.367353      3.812121  on_table_1
7944   8414.469501  -0.224494      3.601750  on_table_1
8027   8414.461871  -0.295923      3.352668  on_table_1
8032   8414.463144  -0.326536      3.219079  on_table_1
8590   8414.471059  -0.214289      3.091645  on_table_1
8620   8414.466846  -0.285719      3.721356  on_table_1
26839  8414.475970  -0.275515      3.187780  on_table_2
26989  8414.474902  -0.357149      3.716826  on_table_2
27169  8414.468165  -0.357149      3.838058  on_table_2
27172  8414.467498  -0.316332      3.171796  on_table_2
27252  8414.468096  -0.295923      3.169444  on_table_2
27352  8414.470386  -0.306128      3.112829  on_table_2
27380  8414.475210  -0.387762      4.202672  on_table_2
27664  8414.470217  -0.275515      3.188745  on_table_2
27852  8414.468802  -0.306128  20413.833984  on_table_2
46196  8414.468571  -0.316332  21376.123047  on_table_3
46381  8414.474946  -0.377557      3.190631  on_table_3
46552  8414.467608  -0.346945      3.056404  on_table_3
46991  8414.469614  -0.255106      3.155153  on_table_3

In [19]:
mars = df[
    (df["Freq"].between(8414.46, 8414.48)) &
    (df["DriftRate"].between(-0.4, -0.2)) &
    (df["status"].str.contains("table"))
]

print(len(mars))

display(
    mars[
        [
            "Freq",
            "DriftRate",
            "SNR",
            "status"
        ]
    ].sort_values("SNR", ascending=False)
)

54

              Freq  DriftRate           SNR      status
46196  8414.468571  -0.316332  21376.123047  on_table_3
27852  8414.468802  -0.306128  20413.833984  on_table_2
7797   8414.468933  -0.285719  13711.767578  on_table_1
7362   8414.462517  -0.255106      4.661358  on_table_1
7080   8414.474289  -0.326536      4.525419  on_table_1
27380  8414.475210  -0.387762      4.202672  on_table_2
7143   8414.474986  -0.316332      3.940798  on_table_1
7252   8414.469418  -0.255106      3.867196  on_table_1
27169  8414.468165  -0.357149      3.838058  on_table_2
7910   8414.476253  -0.367353      3.812121  on_table_1
7643   8414.470812  -0.295923      3.727762  on_table_1
8620   8414.466846  -0.285719      3.721356  on_table_1
26989  8414.474902  -0.357149      3.716826  on_table_2
7225   8414.476172  -0.306128      3.715916  on_table_1
7742   8414.463484  -0.387762      3.676790  on_table_1
7615   8414.468369  -0.265311      3.624114  on_table_1
7435   8414.475334  -0.346945      3.610956  on_table_1
7944   8414.469501  -0.224494      3.601750  on_table_1
7479   8414.463614  -0.336740      3.584651  on_table_1
7710   8414.475604  -0.234698      3.577583  on_table_1
7572   8414.475525  -0.377557      3.559589  on_table_1
7890   8414.466696  -0.204085      3.552514  on_table_1
7212   8414.470472  -0.326536      3.494201  on_table_1
7513   8414.476481  -0.234698      3.460526  on_table_1
7409   8414.469667  -0.234698      3.433796  on_table_1
7618   8414.470425  -0.265311      3.404801  on_table_1
7697   8414.467683  -0.214289      3.367433  on_table_1
7536   8414.462707  -0.214289      3.357026  on_table_1
8027   8414.461871  -0.295923      3.352668  on_table_1
7163   8414.467851  -0.326536      3.333597  on_table_1
7619   8414.470372  -0.265311      3.271367  on_table_1
7396   8414.467026  -0.255106      3.241798  on_table_1
7849   8414.473904  -0.224494      3.231920  on_table_1
8032   8414.463144  -0.326536      3.219079  on_table_1
46381  8414.474946  -0.377557      3.190631  on_table_3
27664  8414.470217  -0.275515      3.188745  on_table_2
26839  8414.475970  -0.275515      3.187780  on_table_2
7686   8414.461936  -0.255106      3.172998  on_table_1
27172  8414.467498  -0.316332      3.171796  on_table_2
27252  8414.468096  -0.295923      3.169444  on_table_2
7390   8414.469711  -0.255106      3.162093  on_table_1
46991  8414.469614  -0.255106      3.155153  on_table_3
7209   8414.466207  -0.224494      3.119859  on_table_1
27352  8414.470386  -0.306128      3.112829  on_table_2
7795   8414.469602  -0.316332      3.108258  on_table_1
8590   8414.471059  -0.214289      3.091645  on_table_1
7496   8414.471744  -0.306128      3.083279  on_table_1
7785   8414.463838  -0.336740      3.078750  on_table_1
7474   8414.468330  -0.357149      3.063644  on_table_1
7282   8414.473118  -0.346945      3.056785  on_table_1
46552  8414.467608  -0.346945      3.056404  on_table_3
7223   8414.466087  -0.204085      3.041044  on_table_1
7434   8414.473073  -0.255106      3.026701  on_table_1
7374   8414.467107  -0.204085      3.020195  on_table_1

In [31]:
import pandas as pd
import os

from turbo_seti.find_event.plot_event_pipeline import plot_event_pipeline


# ============================
# Load BLISS results
# ============================

csv_path = (
    "/home/wlll2x/midres_narrow/mars_single_coarse_bliss/results_mars_single_coarse/"
    "DIAG_Mars2020_f1_snr3_zero.csv"
)

df = pd.read_csv(csv_path)

print(f"Loaded {len(df)} BLISS hits")



# ============================
# Mars2020 expected parameters
# ============================

expected_freq = 8414.4689       # MHz
expected_drift = -0.309         # Hz/s


freq_window = 0.01              # MHz
drift_window = 0.05              # Hz/s



# ============================
# Find Mars-like candidates
# ============================

mars_candidates = df[
    (abs(df["Freq"] - expected_freq) < freq_window) &
    (abs(df["DriftRate"] - expected_drift) < drift_window)
].copy()


print(
    f"Found {len(mars_candidates)} Mars-like candidates"
)


print(
    mars_candidates[
        ["Freq", "DriftRate", "SNR", "status"]
    ]
    .sort_values(
        "SNR",
        ascending=False
    )
    .head(20)
)



# ============================
# Pick strongest Mars candidate
# ============================

if len(mars_candidates) == 0:
    raise RuntimeError(
        "No Mars-like candidates found. Check frequency/drift windows."
    )


best = mars_candidates.sort_values(
    "SNR",
    ascending=False
).iloc[0]


print("\nBest Mars candidate:")
print(best)



# ============================
# Save candidate
# ============================

candidate_csv = (
    "/home/wlll2x/mars_best_candidate.csv"
)


best.to_frame().T.to_csv(
    candidate_csv,
    index=False
)



# ============================
# Plot
# ============================

plot_dir = (
    "/home/wlll2x/mars_best_candidate_plot"
)


os.makedirs(
    plot_dir,
    exist_ok=True
)


plot_event_pipeline(
    candidate_csv,
    "/home/wlll2x/midres_narrow/mars_single_coarse_correct.lst",
    filter_spec="f3",
    user_validation=False,
    plot_dir=plot_dir
)


print("Done!")

Loaded 58938 BLISS hits
Found 30 Mars-like candidates
              Freq  DriftRate           SNR      status
46196  8414.468571  -0.316332  21376.123047  on_table_3
27852  8414.468802  -0.306128  20413.833984  on_table_2
7797   8414.468933  -0.285719  13711.767578  on_table_1
7080   8414.474289  -0.326536      4.525419  on_table_1
7143   8414.474986  -0.316332      3.940798  on_table_1
27169  8414.468165  -0.357149      3.838058  on_table_2
7643   8414.470812  -0.295923      3.727762  on_table_1
8620   8414.466846  -0.285719      3.721356  on_table_1
26989  8414.474902  -0.357149      3.716826  on_table_2
7225   8414.476172  -0.306128      3.715916  on_table_1
7615   8414.468369  -0.265311      3.624114  on_table_1
7435   8414.475334  -0.346945      3.610956  on_table_1
7479   8414.463614  -0.336740      3.584651  on_table_1
7212   8414.470472  -0.326536      3.494201  on_table_1
7618   8414.470425  -0.265311      3.404801  on_table_1
8027   8414.461871  -0.295923      3.352668  on_table_1
7163   8414.467851  -0.326536      3.333597  on_table_1
7619   8414.470372  -0.265311      3.271367  on_table_1
8032   8414.463144  -0.326536      3.219079  on_table_1
27664  8414.470217  -0.275515      3.188745  on_table_2

Best Mars candidate:
Unnamed: 0                     46196
TopHitNum                       7108
DriftRate                  -0.316332
SNR                     21376.123047
Freq                     8414.468571
ChanIndx                      378932
FreqStart                8414.468617
FreqEnd                  8414.468525
CoarseChanNum                      0
FullNumHitsInRange               122
FileID                           NaN
Source                 DIAG_MARS2020
MJD                      59256.78147
RA                    00h00m00.000ss
DEC                    +00d00m00.00s
DELTAT                     18.253611
DELTAF                     -2.793968
max_drift_rate                     0
obs_length                292.057776
Hit_ID                           NaN
status                    on_table_3
in_n_ons                         NaN
RFI_in_range                     NaN
delta_t                       1254.0
Name: 46196, dtype: object
plot_event_pipeline: Opened file /home/wlll2x/mars_best_candidate.csv
plot_event_pipeline: file = spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66265_DIAG_Mars2020_0011.rawspec.0000_diced.hits.h5, tstart = 59256.76695601852, source_name = DIAG_Mars2020
plot_event_pipeline: file = spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66578_DIAG_Mars_0012.rawspec.0000_diced.hits.h5, tstart = 59256.770578703705, source_name = DIAG_Mars
plot_event_pipeline: file = spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66892_DIAG_Mars2020_0013.rawspec.0000_diced.hits.h5, tstart = 59256.77421296296, source_name = DIAG_Mars2020
plot_event_pipeline: file = spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67205_DIAG_Mars_0014.rawspec.0000_diced.hits.h5, tstart = 59256.77783564815, source_name = DIAG_Mars
plot_event_pipeline: file = spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67519_DIAG_Mars2020_0015.rawspec.0000_diced.hits.h5, tstart = 59256.78146990741, source_name = DIAG_Mars2020
plot_event_pipeline: file = spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67832_DIAG_Mars_0016.rawspec.0000_diced.hits.h5, tstart = 59256.785092592596, source_name = DIAG_Mars
Plotting some events for:  DIAG_MARS2020
There are 1 total events in the csv file /home/wlll2x/mars_best_candidate.csv
therefore, you are about to make 1 .png files.
plot_event      INFO     plot_candidate_events: elapsed time = 1.04 seconds
Done!

In [5]:
import pandas as pd
import glob
import matplotlib.pyplot as plt

target_freq = 8414.46861  # MHz
window = 5.0              # MHz

files = glob.glob(
    "/datax/scratch/wlll2x/mars_midres_bliss/*.dat"
)

columns = [
    "hit",
    "drift_rate",
    "snr",
    "freq",
    "corrected_freq",
    "index",
    "freq_start",
    "freq_end",
    "sefd_freq",
    "coarse_channel",
    "full_number_hits",
    "extra"
]

hits = []

for f in files:
    df = pd.read_csv(
        f,
        comment="#",
        sep=r"\s+",
        header=None
    )

    df.columns = columns
    df["file"] = f
    hits.append(df)

df = pd.concat(hits, ignore_index=True)


# Select only hits near Mars frequency
near_mars = df[
    abs(df["freq"] - target_freq) < window
]


print(f"Total BLISS hits: {len(df)}")
print(f"Hits within ±{window} MHz of Mars: {len(near_mars)}")

print(
    near_mars[
        [
            "freq",
            "drift_rate",
            "snr",
            "full_number_hits",
            "file"
        ]
    ].sort_values("snr", ascending=False)
)


# Plot if anything exists
if len(near_mars) > 0:

    plt.figure(figsize=(10,6))

    plt.scatter(
        near_mars["freq"],
        near_mars["snr"],
        c=near_mars["drift_rate"],
        s=80
    )

    plt.axvline(
        target_freq,
        linestyle="--",
        label="Expected Mars frequency"
    )

    plt.xlabel("Frequency (MHz)")
    plt.ylabel("SNR")
    plt.colorbar(label="Drift rate (Hz/s)")
    plt.legend()
    plt.title(
        f"BLISS hits within ±{window} MHz of Mars frequency"
    )

    plt.show()

else:
    print("No BLISS hits found")

Total BLISS hits: 4296
Hits within ±5.0 MHz of Mars: 0
Empty DataFrame
Columns: [freq, drift_rate, snr, full_number_hits, file]
Index: []
No BLISS hits found in this frequency window.

# MidRes Plotter

In [3]:
import pandas as pd

df = pd.read_csv(
    "/datax/scratch/wlll2x/mars_midres_bliss/spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66265_DIAG_Mars2020_0011.rawspec.0002.dat",
    comment="#",
    sep=r"\s+",
    header=None
)

df.columns = [
    "Top_Hit_#",          # hit number
    "Drift_Rate",
    "SNR",
    "Freq",
    "Freq_start",
    "Index",
    "freq_start",
    "freq_end",
    "SEFD",
    "Coarse",
    "NumHits",
    "Extra"
]

print(df.head())

   Top_Hit_#  Drift_Rate          SNR          Freq    Freq_start  Index  \
0          1   -9.584659   209.795883  11249.403472  11249.403472    721
1          2   19.169318   168.086914  11249.708186  11249.708186    612
2          3   19.169318  7632.635254  11249.708186  11249.708186    618
3          4   47.923296   145.654922  11249.403502  11249.403502    724
4          5   47.923296   114.932007  11249.403502  11249.403502    725

     freq_start      freq_end  SEFD  Coarse  NumHits  Extra
0  11249.404907  11249.402036   0.0     0.0        0      6
1  11249.705315  11249.711057   0.0     0.0        0     12
2  11249.705315  11249.711057   0.0     0.0        0     12
3  11249.396324  11249.410681   0.0     0.0        0      9
4  11249.396324  11249.410681   0.0     0.0        0      9

In [4]:
candidate = df.iloc[[100]]

candidate.to_csv(
    "/home/wlll2x/midres_candidate.csv",
    index=False
)

candidate

,Top_Hit_#,Drift_Rate,SNR,Freq,Freq_start,Index,freq_start,freq_end,SEFD,Coarse,NumHits,Extra
100,101,0.0,459.125458,11239.013672,11239.013672,281,11239.013672,11239.013672,0.0,0.0,4,157

In [2]:
from turbo_seti.find_event.find_event_pipeline import find_event_pipeline

events = find_event_pipeline(
    dat_file_list_str="mars_dat.lst",
    h5_file_list_str="mars_h5.lst",
    number_in_cadence=6,
    on_off_first="ON",

    check_zero_drift=True,

    filter_threshold=1,

    saving=True,
    csv_name="midres_events.csv"
)

print(events)

===========   BEGINNING FIND_EVENT PIPELINE   ===========

Assuming the first observation is an ON

FileNotFoundError: [Errno 2] No such file or directory: 'mars_dat.lst'

# Average Spectrum:

# Brightest Channel Track:

# Independent Drift Fitting

# Bliss Comparison: